//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.1.
//


package com.useridentify.service;

import android.app.NotificationManager;
import android.content.Context;
import org.androidannotations.api.builder.ServiceIntentBuilder;

public final class IdenNotifyService_
    extends IdenNotifyService
{


    public static IdenNotifyService_.IntentBuilder_ intent(Context context) {
        return new IdenNotifyService_.IntentBuilder_(context);
    }

    private void init_() {
        notificationManager = ((NotificationManager) this.getSystemService(Context.NOTIFICATION_SERVICE));
    }

    @Override
    public void onCreate() {
        init_();
        super.onCreate();
    }

    public static class IntentBuilder_
        extends ServiceIntentBuilder<IdenNotifyService_.IntentBuilder_>
    {


        public IntentBuilder_(Context context) {
            super(context, IdenNotifyService_.class);
        }

    }

}
